# HappyBees Container Orchestration
# Run: podman-compose up -d

version: "3.8"

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: happybees-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: happybees_dev
      POSTGRES_DB: happybees
    ports:
      - "5432:5432"
    volumes:
      - happybees_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Containerfile
    container_name: happybees-backend
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:happybees_dev@timescaledb:5432/happybees
    ports:
      - "8000:8000"
    depends_on:
      timescaledb:
        condition: service_healthy
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Containerfile
    container_name: happybees-dashboard
    command: python -m backend.dashboard.app --node pico-hive-001 --api http://backend:8000/api/v1
    ports:
      - "8050:8050"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  happybees_pgdata:
